# Generated by Django 3.2.6 on 2021-08-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
