# Generated by Django 3.2.6 on 2021-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturlsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinks',
            name='redirect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
