# Generated by Django 3.2.6 on 2021-08-08 19:28

from django.db import migrations, models
import shorturlsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturlsapp', '0003_alter_shortlinks_rnd_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinks',
            name='origin_url',
            field=models.CharField(max_length=255, validators=[shorturlsapp.models.ShortLinks.validate_url]),
        ),
        migrations.AlterField(
            model_name='shortlinks',
            name='rnd_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
